### ISSUE TITLE
[Bug] Validator stoped with this error

### ISSUE THREAD

**Issue by liangping** [OLSF/libra#851]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
2021-11-21T00:44:13.178912Z ERROR language/diem-vm/src/data_cache.rs:91 [VM, StateView] Error getting data from storage for AccessPath { address: 000000000│ inner: Inner { kind: Request, source: Some(ConnectionFailed("Connection refused (
00000000000000000000000, path: 01000000000000000000000000000000010a4469656d436f6e6669670a4469656d436f6e6669670107000000000000000000000000000000010c4469656d│os error 111)")), json_rpc_error: None } }
564d436f6e6669670c4469656d564d436f6e66696700 } {"block_id":"3753e5d6164f873cdf2d68cfc88574b31f4e68c9b47522401ed3bca527cca8a8","name":"execution","txn_id":0│
}                                                                                                                                                          │Caused by:
2021-11-21T00:44:13.179401Z ERROR language/diem-vm/src/data_cache.rs:91 [VM, StateView] Error getting data from storage for AccessPath { address: 000000000│    Connection Failed: Connection refused (os error 111)
00000000000000000000000, path: 01000000000000000000000000000000010a4469656d436f6e6669670a4469656d436f6e6669670107000000000000000000000000000000010b4469656d│Mining VDF Proof # 1190
56657273696f6e0b4469656d56657273696f6e00 } {"block_id":"3753e5d6164f873cdf2d68cfc88574b31f4e68c9b47522401ed3bca527cca8a8","name":"execution","txn_id":0}   │Delay: 1646 seconds
2021-11-21T00:44:13.179683Z ERROR language/diem-vm/src/data_cache.rs:91 [VM, StateView] Error getting data from storage for AccessPath { address: 000000000│Proof mined: proof_1190.json created.
00000000000000000000000, path: 01000000000000000000000000000000010a4469656d436f6e6669670a4469656d436f6e6669670107000000000000000000000000000000011f4469656d│Fetching remote tower height: http://localhost:8080/, 8421CB22E56F687395F5973BBF0C
5472616e73616374696f6e5075626c697368696e674f7074696f6e1f4469656d5472616e73616374696f6e5075626c697368696e674f7074696f6e00 } {"block_id":"3753e5d6164f873cdf2│BDFB
d68cfc88574b31f4e68c9b47522401ed3bca527cca8a8","name":"execution","txn_id":0}                                                                              │Error fetching remote state: Error { inner: Inner { kind: Request, source: Some(Co
========================================== 73558 ==========================================                                                                │nnectionFailed("Connection refused (os error 111)")), json_rpc_error: None } }
2021-11-21T00:44:13.181257Z ERROR language/diem-vm/src/data_cache.rs:91 [VM, StateView] Error getting data from storage for AccessPath { address: 000000000│
00000000000000000000001, path: 0000000000000000000000000000000001094469656d426c6f636b } {"block_id":"3753e5d6164f873cdf2d68cfc88574b31f4e68c9b47522401ed3bc│Caused by:
a527cca8a8","name":"execution","txn_id":0}                                                                                                                 │    Connection Failed: Connection refused (os error 111)
2021-11-21T00:44:13.181413Z ERROR language/diem-vm/src/errors.rs:183 [diem_vm] Unexpected error from known Move function, 'block_prologue'. Error: ERROR { │ERROR: Failed fetching remote state, message: Error fetching remote state: Error {
status_code: UNKNOWN_INVARIANT_VIOLATION_ERROR } {"block_id":"3753e5d6164f873cdf2d68cfc88574b31f4e68c9b47522401ed3bca527cca8a8","name":"execution","txn_id"│ inner: Inner { kind: Request, source: Some(ConnectionFailed("Connection refused (
:0}                                                                                                                                                        │os error 111)")), json_rpc_error: None } }
2021-11-21T00:44:13.185073Z [consensus] ERROR common/crash-handler/src/lib.rs:38 details = '''panicked at '[BlockStore] failed to insert block during build│
 Internal error: "status UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION of type Invariant violation"', consensus/src/block_storage/block_store.rs:184:21'''     │Caused by:
backtrace = '''                                                                                                                                            │    Connection Failed: Connection refused (os error 111)
   0:     0x563d8e86bb2c - backtrace::capture::Backtrace::new::ha92e72667ec9fb7e                                                                           │Mining VDF Proof # 1191
   1:     0x563d8e93130e - crash_handler::handle_panic::h6528425d40da96ce                                                                                  │Delay: 1648 seconds
   2:     0x563d8e93128a - crash_handler::setup_panic_handler::{{closure}}::h2c9ce01f757d6013                                                              │Proof mined: proof_1191.json created.
   3:     0x563d8edacb87 - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8                                                                         │Fetching remote tower height: http://localhost:8080/, 8421CB22E56F687395F5973BBF0C
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17                                      │BDFB
   4:     0x563d8edc8bf3 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da                                                             │Error fetching remote state: Error { inner: Inner { kind: Request, source: Some(Co
   5:     0x563d8edc8b6c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128                                                       │nnectionFailed("Connection refused (os error 111)")), json_rpc_error: None } }
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18                           │
   6:     0x563d8edc8b1d - rust_begin_unwind                                                                                                               │Caused by:
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5                                       │    Connection Failed: Connection refused (os error 111)
   7:     0x563d8edad580 - std::panicking::begin_panic_fmt::h400b8e9dca200408                                                                              │ERROR: Failed fetching remote state, message: Error fetching remote state: Error {
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5                                       │ inner: Inner { kind: Request, source: Some(ConnectionFailed("Connection refused (
   8:     0x563d8e8ff75a - consensus::block_storage::block_store::BlockStore::build::{{closure}}::h17c74e74e74a2454                                        │os error 111)")), json_rpc_error: None } }
   9:     0x563d8e8ff526 - consensus::block_storage::block_store::BlockStore::build::h59672584502ca6f8                                                     │
  10:     0x563d8e8f20d9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he11131313abb19e9                           │Caused by:
  11:     0x563d8e8e5567 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8e3faad9146fcaf4                           │    Connection Failed: Connection refused (os error 111)
  12:     0x563d8e909965 - tokio::runtime::task::harness::poll_future::hd80c40729621f843                                                                   │Mining VDF Proof # 1192
  13:     0x563d8e909692 - tokio::runtime::task::raw::poll::h015938a9336a50ab                                                                              │Delay: 1647 seconds
  14:     0x563d8edebc58 - tokio::runtime::thread_pool::worker::Context::run_task::h9108183345588446                                                       │Proof mined: proof_1192.json created.
  15:     0x563d8edf6468 - tokio::runtime::task::raw::poll::h0c81b8769eb62609                                                                              │Fetching remote tower height: http://localhost:8080/, 8421CB22E56F687395F5973BBF0C
  16:     0x563d8edf0490 - std::sys_common::backtrace::__rust_begin_short_backtrace::h20be9e383db8b6fe                                                     │BDFB
  17:     0x563d8edf1b39 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h91085810c12e01b2                                                        │Error fetching remote state: Error { inner: Inner { kind: Request, source: Some(Co
  18:     0x563d8edd69b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc444a77f8dd8d825                                     │nnectionFailed("Connection refused (os error 111)")), json_rpc_error: None } }
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9                                        │
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8b68a0a9a2093dfc                                     │Caused by:
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9                                        │    Connection Failed: Connection refused (os error 111)
                           std::sys::unix::thread::Thread::new::thread_start::hb95464447f61f48d                                                            │ERROR: Failed fetching remote state, message: Error fetching remote state: Error {
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17                                 │ inner: Inner { kind: Request, source: Some(ConnectionFailed("Connection refused (
  19:     0x7f350543e609 - start_thread                                                                                                                    │os error 111)")), json_rpc_error: None } }
  20:     0x7f3504e8a293 - clone                                                                                                                           │
  21:                0x0 - <unknown>  
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by mortonbits** [comment]
Just to check the criticality: Does this happen also after restart? Or was it a one time failure so far?

**Comment by liangping** [comment]
@mortonbits Yeah. but seems it's fixed on latest version.

**Comment by 0o-de-lally** [comment]
I've never seen this error in a running node. Only in transactions or tests.

But the logs above it are also interesting. Seems like you are getting storage errors, and it's not finding expected state.

**Comment by liangping** [comment]
> I've never seen this error in a running node. Only in transactions or tests.
> 
> But the logs above it are also interesting. Seems like you are getting storage errors, and it's not finding expected state.

Yeah, The root state is pruned.
